services:
  ia_check_output:
    hostname:         ia_check_output.innovanon.com
    build:
      context:        .
      tags:
        - ia_check_output:latest
    restart:          no
    logging:
      driver:         syslog   
